spring:
  profiles:
    active:
    - dev
    


--- 
server:
  port: 80

spring:
  
  profiles: dev
 
  datasource:
    url: jdbc:mysql://localhost:3306/Arachne_db?useSSL=false
    username: ksr_arachne_dev
    password: arachne_password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      
      
---      
  
spring:
  profiles: product
    
server:
  port: 8443
  ssl:  
    key-store: classpath:mykeys.jks
    key-store-password: arachne
    key-password: arachne

---

